os: linux
dist: xenial
sudo: true
language: python
python: "3.7"

services:
    - docker

env:
    - CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

install:
    - pip install conan_package_tools

script:
    - python build.py
